version: '3.8'

services:
  frontend:
    build:
      context: ./battleship-frontend
    ports:
      - "4200:80"

  backend:
    build:
      context: ./BattleshipBackend
    ports:
      - "5000:80"